// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/worker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkerService_ProcessModel_FullMethodName  = "/worker.WorkerService/ProcessModel"
	WorkerService_ConvertToCAD_FullMethodName  = "/worker.WorkerService/ConvertToCAD"
	WorkerService_GenerateModel_FullMethodName = "/worker.WorkerService/GenerateModel"
	WorkerService_OptimizeModel_FullMethodName = "/worker.WorkerService/OptimizeModel"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerServiceClient interface {
	ProcessModel(ctx context.Context, in *ProcessModelRequest, opts ...grpc.CallOption) (*ProcessModelResponse, error)
	ConvertToCAD(ctx context.Context, in *ConvertToCADRequest, opts ...grpc.CallOption) (*ConvertToCADResponse, error)
	GenerateModel(ctx context.Context, in *GenerateModelRequest, opts ...grpc.CallOption) (*GenerateModelResponse, error)
	OptimizeModel(ctx context.Context, in *OptimizeModelRequest, opts ...grpc.CallOption) (*OptimizeModelResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) ProcessModel(ctx context.Context, in *ProcessModelRequest, opts ...grpc.CallOption) (*ProcessModelResponse, error) {
	out := new(ProcessModelResponse)
	err := c.cc.Invoke(ctx, WorkerService_ProcessModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ConvertToCAD(ctx context.Context, in *ConvertToCADRequest, opts ...grpc.CallOption) (*ConvertToCADResponse, error) {
	out := new(ConvertToCADResponse)
	err := c.cc.Invoke(ctx, WorkerService_ConvertToCAD_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GenerateModel(ctx context.Context, in *GenerateModelRequest, opts ...grpc.CallOption) (*GenerateModelResponse, error) {
	out := new(GenerateModelResponse)
	err := c.cc.Invoke(ctx, WorkerService_GenerateModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) OptimizeModel(ctx context.Context, in *OptimizeModelRequest, opts ...grpc.CallOption) (*OptimizeModelResponse, error) {
	out := new(OptimizeModelResponse)
	err := c.cc.Invoke(ctx, WorkerService_OptimizeModel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
type WorkerServiceServer interface {
	ProcessModel(context.Context, *ProcessModelRequest) (*ProcessModelResponse, error)
	ConvertToCAD(context.Context, *ConvertToCADRequest) (*ConvertToCADResponse, error)
	GenerateModel(context.Context, *GenerateModelRequest) (*GenerateModelResponse, error)
	OptimizeModel(context.Context, *OptimizeModelRequest) (*OptimizeModelResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) ProcessModel(context.Context, *ProcessModelRequest) (*ProcessModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessModel not implemented")
}
func (UnimplementedWorkerServiceServer) ConvertToCAD(context.Context, *ConvertToCADRequest) (*ConvertToCADResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertToCAD not implemented")
}
func (UnimplementedWorkerServiceServer) GenerateModel(context.Context, *GenerateModelRequest) (*GenerateModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateModel not implemented")
}
func (UnimplementedWorkerServiceServer) OptimizeModel(context.Context, *OptimizeModelRequest) (*OptimizeModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptimizeModel not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_ProcessModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ProcessModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ProcessModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ProcessModel(ctx, req.(*ProcessModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ConvertToCAD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertToCADRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ConvertToCAD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ConvertToCAD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ConvertToCAD(ctx, req.(*ConvertToCADRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GenerateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GenerateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GenerateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GenerateModel(ctx, req.(*GenerateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_OptimizeModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).OptimizeModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_OptimizeModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).OptimizeModel(ctx, req.(*OptimizeModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "worker.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessModel",
			Handler:    _WorkerService_ProcessModel_Handler,
		},
		{
			MethodName: "ConvertToCAD",
			Handler:    _WorkerService_ConvertToCAD_Handler,
		},
		{
			MethodName: "GenerateModel",
			Handler:    _WorkerService_GenerateModel_Handler,
		},
		{
			MethodName: "OptimizeModel",
			Handler:    _WorkerService_OptimizeModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/worker.proto",
}
